title: Something.
author: CatMaster
email: catmaster3645@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about any and all topics.

# social links
twitter_username: catmaster3645
github_username:  CatMaster3645

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
